version: "3.5"

services:

  php:
    build:
      context: php
    ports:
    - "80:80"
    volumes:
    - "./app:/var/www/html"

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pw
    volumes:
    - ./databases/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - "127.0.0.1:8080:8080"
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: user_pw
